spring:
  application:
    name: payment-service
  datasource:
    username: mikasa
    password: mikasa
    url: jdbc:postgresql://localhost:5432/payment
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}