spring:
  data:
    mongodb:
      username: ${SPRING_DATA_MONGODB_USERNAME:mikasa}
      password: ${SPRING_DATA_MONGODB_PASSWORD:mikasa}
      database: ${SPRING_DATA_MONGODB_DATABASE:customer}
server:
  port: ${SERVER_PORT:8090}
