spring:
  data:
    mongodb:
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      database: ${SPRING_DATA_MONGODB_DATABASE}
server:
  port: ${SERVER_PORT}
