spring:
  data:
    mongodb:
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      database: ${SPRING_DATA_MONGODB_DATABASE}
  kafka:
    consumer:
      group-id: paymentGroup.orderGroup
      properties:
        spring.json.trusted.package: "*"
        spring.json.type.mapping: orderConfirmation:com.ecommer.email.model.dto, paymentConfirmation:com.ecommer.email.model.dto
  mail:
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

server:
  port: 8040
