spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:mikasa}
    password: ${SPRING_DATASOURCE_PASSWORD:mikasa}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    producer.properties:
      spring.json.type.mapping: orderConfirmation:com.ecommer.order.model.response.OrderConfirmation
application:
  config:
    customer-url: http://:localhost8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payments
    product-url: http://localhost:8222/api/v1/products
server:
  port: 8070
