spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:mikasa}
    password: ${SPRING_DATASOURCE_PASSWORD:mikasa}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payment}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.ecommer.payment.model.request.PaymentNotificationRequest
application:
  config:
    product-url: http://localhost:8222/api/v1/products
server:
  port: 8060