CREATE TABLE IF NOT EXISTS CATEGORY
(
    ID          INTEGER NOT NULL PRIMARY KEY,
    NAME        VARCHAR(255),
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID                 INTEGER NOT NULL PRIMARY KEY,
    AVAILABLE_QUANTITY INTEGER,
    NAME               VARCHAR(255),
    DESCRIPTION        VARCHAR(255),
    PRICE              DECIMAL(38, 2),
    CATEGORY_ID        INTEGER NOT NULL,

    CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);
