CREATE TABLE IF NOT EXISTS CUSTOMER_ORDER
(
    ID             INTEGER                  NOT NULL PRIMARY KEY,
    REFERENCE      VARCHAR(255) UNIQUE      NOT NULL,
    TOTAL_AMOUNT   NUMERIC(38, 2),
    PAYMENT_METHOD VARCHAR(255)             NOT NULL,
    CUSTOMER_ID    VARCHAR(255),
    CREATED_TIME   TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATE_TIME    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMER_ORDER_LINE
(
    ID         INTEGER NOT NULL PRIMARY KEY,
    ORDER_ID   INTEGER REFERENCES CUSTOMER_ORDER (ID),
    PRODUCT_ID INTEGER,
    QUANTITY   DOUBLE PRECISION
);

CREATE SEQUENCE IF NOT EXISTS CUSTOMER_ORDER_SEQ INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS CUSTOMER_LINE_SEQ INCREMENT BY 50;