spring:
  profiles:
    active: git, vault
  application:
    name: config-server
  cloud:
    config:
      allow-override: true
      server:
        vault:
          host: ${VAULT_HOST:localhost}
          port: ${VAULT_PORT:8200}
          order: 1
          kv-version: 1
          authentication: token
          profile-separator: '/'
          backend: backend-service-dev
          token: ${VAULT_TOKEN:hvs.QNuvr1HyDQ5VHZkNMKCQCIxa}
          scheme: ${VAULT_SCHEME:http}
        git:
          uri: ${GIT_URL:https://github.com/teukumunawark/microservices-mono-repo}
          username: ${GIT_USERNAME:teukumunawark}
          password: ${GIT_PASSWORD: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}
          skip-ssl-validation: true
          default-label: main
          order: 2
          search-paths: 'services/config-map'


server:
  port: 8888
