CREATE TABLE IF NOT EXISTS PAYMENT
(
    ID             INTEGER                  NOT NULL PRIMARY KEY,
    AMOUNT         NUMERIC(38, 2),
    PAYMENT_METHOD VARCHAR(255)             NOT NULL,
    ORDER_ID       INTEGER                  NOT NULL,
    CREATED_TIME   TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_TIME   TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE IF NOT EXISTS PAYMENT_SEQ INCREMENT BY 50;